### ISSUE TITLE
Windows or Ubuntus ？Which version of PyTorch?

### ISSUE THREAD

**Issue by Amireux52** [IamMRM/Convolutional-Neural-Networks-for-Direct-Text-Deblurring#1]
Thank you for your work! Is the code implemented on Windows or Ubuntus ？Which version of PyTorch is required?Looking forward to your reply,

**Comment by IamMRM** [comment]
> Thank you for your work! Is the code implemented on Windows or Ubuntus ？Which version of PyTorch is required?Looking forward to your reply,

It is implemented on windows but with a command prompt. Also for Pytorch version, you can use 1.7.1 to work this code.

**Comment by Amireux52** [comment]
Thanks, I'll try


| |
15755329512
|
|
***@***.***
|
签名由网易邮箱大师定制
On 10/28/2021 14:18，Muhammad Roshan ***@***.***> wrote：

Thank you for your work! Is the code implemented on Windows or Ubuntus ？Which version of PyTorch is required?Looking forward to your reply,

It is implemented on windows but with a command prompt. Also for Pytorch version, you can use 1.7.1 to work this code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
